from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, date
from enum import Enum
from typing import Optional, Any

import pandas as pd


class SignalDirection(Enum):
    """Direction of a trading signal."""
    LONG = "long"
    SHORT = "short"
    NEUTRAL = "neutral"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        symbol: Stock symbol
        direction: Buy, sell, or neutral
        confidence: Confidence score from 0 to 1
        strategy: Name of the strategy that generated this signal
        timestamp: When the signal was generated
        entry_price: Suggested entry price
        stop_loss: Suggested stop loss price
        take_profit: Suggested take profit price
        timeframe: Timeframe the signal was generated on
        metadata: Additional strategy-specific data
    """
    symbol: str
    direction: SignalDirection
    confidence: float
    strategy: str
    timestamp: datetime = field(default_factory=datetime.now)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    timeframe: str = "1h"
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")

    def is_actionable(self, threshold: float = 0.6) -> bool:
        """Check if signal meets the confidence threshold."""
        return (
            self.direction != SignalDirection.NEUTRAL
            and self.confidence >= threshold
        )

    def to_dict(self) -> dict:
        """Convert signal to dictionary."""
        return {
            "symbol": self.symbol,
            "direction": self.direction.value,
            "confidence": self.confidence,
            "strategy": self.strategy,
            "timestamp": self.timestamp.isoformat(),
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "timeframe": self.timeframe,
            "metadata": self.metadata
        }


@dataclass
class OptionsSignal(Signal):
    """
    Extended signal for options strategies.

    Inherits all Signal attributes and adds options-specific fields.

    Additional Attributes:
        contract_symbol: Full OCC option symbol (e.g., "AAPL230120C00150000")
        contract_type: "call" or "put"
        strike: Strike price
        expiration: Expiration date
        premium: Option premium price
        max_risk: Maximum risk for the position
        max_profit: Maximum profit for the position
        legs: List of OptionLeg objects for multi-leg strategies
        greeks: OptionGreeks for this contract
    """
    contract_symbol: Optional[str] = None
    contract_type: Optional[str] = None
    strike: Optional[float] = None
    expiration: Optional[date] = None
    premium: Optional[float] = None
    max_risk: Optional[float] = None
    max_profit: Optional[float] = None
    legs: Optional[list] = None  # List of OptionLeg objects
    greeks: Optional[Any] = None  # OptionGreeks object

    def to_dict(self) -> dict:
        """Convert options signal to dictionary."""
        base_dict = super().to_dict()
        base_dict.update({
            "contract_symbol": self.contract_symbol,
            "contract_type": self.contract_type,
            "strike": self.strike,
            "expiration": self.expiration.isoformat() if self.expiration else None,
            "premium": self.premium,
            "max_risk": self.max_risk,
            "max_profit": self.max_profit,
            "legs_count": len(self.legs) if self.legs else 0
        })
        return base_dict


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement:
    - name property: Unique identifier for the strategy
    - analyze(): Generate signals for a list of symbols
    - get_signal(): Generate a signal for a single symbol
    """

    def __init__(self):
        self._enabled: bool = True
        self._weight: float = 1.0
        self._last_signals: dict[str, Signal] = {}

    @property
    @abstractmethod
    def name(self) -> str:
        """Unique name identifier for this strategy."""
        pass

    @property
    def enabled(self) -> bool:
        """Whether the strategy is currently enabled."""
        return self._enabled

    @enabled.setter
    def enabled(self, value: bool) -> None:
        self._enabled = value

    @property
    def weight(self) -> float:
        """Current weight in the voting system."""
        return self._weight

    @weight.setter
    def weight(self, value: float) -> None:
        self._weight = max(0.0, min(1.0, value))

    @abstractmethod
    def analyze(self, symbols: list[str]) -> list[Signal]:
        """
        Analyze multiple symbols and generate signals.

        Args:
            symbols: List of stock symbols to analyze

        Returns:
            List of Signal objects for symbols with actionable signals
        """
        pass

    @abstractmethod
    def get_signal(self, symbol: str, data: pd.DataFrame) -> Signal:
        """
        Generate a signal for a single symbol given its price data.

        Args:
            symbol: Stock symbol
            data: DataFrame with OHLCV data

        Returns:
            Signal object with direction and confidence
        """
        pass

    def get_required_bars(self) -> int:
        """
        Get the minimum number of bars required for analysis.

        Override this in subclasses if strategy needs more historical data.
        """
        return 100

    def get_timeframes(self) -> list[str]:
        """
        Get the timeframes this strategy analyzes.

        Override this for multi-timeframe strategies.
        """
        return ["1h"]

    def should_exit(self, symbol: str, data: pd.DataFrame) -> tuple[bool, str]:
        """
        Check if the strategy suggests exiting a position.

        Args:
            symbol: Stock symbol
            data: DataFrame with OHLCV data

        Returns:
            Tuple of (should_exit, reason)
        """
        return False, ""

    def get_last_signal(self, symbol: str) -> Optional[Signal]:
        """Get the last signal generated for a symbol."""
        return self._last_signals.get(symbol)

    def _cache_signal(self, signal: Signal) -> None:
        """Cache a signal for later reference."""
        self._last_signals[signal.symbol] = signal

    def reset(self) -> None:
        """Reset strategy state."""
        self._last_signals.clear()

    def get_parameters(self) -> dict[str, Any]:
        """
        Get strategy parameters.

        Override this to return strategy-specific parameters.
        """
        return {
            "name": self.name,
            "enabled": self.enabled,
            "weight": self.weight,
            "required_bars": self.get_required_bars(),
            "timeframes": self.get_timeframes()
        }

    def set_parameters(self, params: dict[str, Any]) -> None:
        """
        Set strategy parameters.

        Override this to handle strategy-specific parameters.
        """
        if "enabled" in params:
            self.enabled = params["enabled"]
        if "weight" in params:
            self.weight = params["weight"]

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}("
            f"name={self.name}, "
            f"enabled={self.enabled}, "
            f"weight={self.weight})"
        )
